## /etc/prometheus/prometheus.yml

# global:
#   scrape_interval: 5s
#   evaluation_interval: 5s

# rule_files:
#   - /etc/prometheus/rules.yml

# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
#       - localhost:9093

# scrape_configs:
#   - job_name: 'prometheus'
#     ec2_sd_configs:
#       - region: us-east-1
#         port: 9100
#         filters:
#           - name: tag:Project
#             values: [Udapeople]
#     relabel_configs:
#       - source_labels: [__meta_ec2_tag_Project, __meta_ec2_tag_Name]
#         separator: "_"
#         target_label: instance
#       - source_labels: [__meta_ec2_instance_id]
#         target_label: instance_id
#       - source_labels: [__meta_ec2_public_dns_name]
#         target_label: public_dns_name

## /etc/prometheus/alertmanager.yml
global:
  resolve_timeout: 1m

route:
  group_by: [Alertname] 
  receiver: alert-me

receivers:
- name: alert-me
  email_configs:
  - to: mahmoud.elneweshy@nagwa.com
    from: mahmoud.elneweshy@nagwa.com
    send_resolved: true
    smarthost: smtp.gmail.com:587
    auth_username: mahmoud.elneweshy@nagwa.com
    auth_identity: mahmoud.elneweshy@nagwa.com
    auth_password: 

## /etc/systemd/system/alertmanager.service
# [Unit]
# Description=Alert Manager
# Wants=network-online.target
# After=network-online.target

# [Service]
# Type=simple
# User=prometheus
# Group=prometheus
# ExecStart=/usr/local/bin/alertmanager \
#   --config.file=/etc/prometheus/alertmanager.yml \
#   --storage.path=/var/lib/alertmanager

# Restart=always

# [Install]
# WantedBy=multi-user.target


## /etc/systemd/system/node_exporter.service
# [Unit]
# Description=Prometheus Node Exporter Service
# After=network.target

# [Service]
# User=node_exporter
# Group=node_exporter
# Type=simple
# ExecStart=/usr/local/bin/node_exporter

# [Install]
# WantedBy=multi-user.target

## /etc/prometheus/rules.yml
# groups:
# - name: Down
#   rules:
#   - alert: InstanceDown
#     expr: up == 0
#     for: 1m
#     labels:
#       severity: 'critical'
#     annotations:
#       summary: "Instance {{ $labels.instance }} down"
#       description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."